# More documentation about how to customize your build
# can be found here:
# https://docs.fastlane.tools
fastlane_version "1.109.0"

# This value helps us track success metrics for Fastfiles
# we automatically generate. Feel free to remove this line
# once you get things running smoothly!
generated_fastfile_id "0c5f6285-7b94-47eb-92dc-0305fd3a40e0"

default_platform :ios

desc "Build a develop app"
lane :develop do
  gym(
    scheme: "TravisTest",
    export_method: "ad-hoc"
  )
end

lane :qa do
  # build your iOS app
  gym(
    scheme: "TravisTestQa",
    export_method: "ad-hoc"
  )

  # upload to Beta by Crashlytics
  crashlytics(
    api_token: "bdb81c700d9922a3e5487434e555eb2ef28f5f85",
    build_secret: "a502db77fbe547962e53ec7d855e4c8ef8318b491824d07c4518503ac02f950a"
  )
end

lane :production do
  gym(
    scheme: "TravisTestProduction",
    export_method: "ad-hoc"
  )
end

lane :app_store do
  gym(
    scheme: "TravisTestAppStore",
    export_method: "ad-hoc"
  )
end
